import { readFileSync } from 'node:fs';
import { JSDOM } from 'jsdom';
const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const dom = new JSDOM(html, { url: 'http://localhost/', pretendToBeVisual: true, runScripts: 'outside-only' });
global.window = dom.window;
global.document = dom.window.document;
global.localStorage = dom.window.localStorage;
global.requestAnimationFrame = dom.window.requestAnimationFrame.bind(dom.window);
await import('../src/main.js');
const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
window.document.querySelector('.module-card.library').click();
console.log('library?', !!$('.library'));
console.log('cards:', $$('.entry-card').length, 'favBtns:', $$('.entry-card .fav-btn').length);
const first = $$('.entry-card .fav-btn')[0];
console.log('first fav class before:', first?.className, 'data-id:', first?.closest('.entry-card')?.getAttribute('data-id'));
first.click();
const again = $$('.entry-card .fav-btn')[0];
console.log('first fav class after:', again?.className);
console.log('fav storage:', window.localStorage.getItem('gang-ai:favorites:v1'));
process.exit(0);
